# Generated by Django 4.2 on 2024-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='logo_vet',
            field=models.ImageField(default=-2020, upload_to='veterinarias/'),
            preserve_default=False,
        ),
    ]
